site_name: TIL - Seiichi Yonezawa

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      auto_title: true
  - pymdownx.superfences
  - pymdownx.tilde
